Don't push stats to feed_queue
only store the post-reception job.

The stats data can be huge, so the push-pull-push cycle
through feed_queue is not optimal ... and in practice
causes web2py trouble when fetching the data blob back
from the queue.

Traceback (most recent call last):
 File "applications/feed/controllers/default.py", line 3010, in feed_dequeue
    entries = db(db.feed_queue.id>0).select(limitby=(0,1))
  File "/soft/collector_opensvc/apps/web2py/gluon/dal.py", line 6333, in select
    return self.db._adapter.select(self.query,fields,attributes)
  File "/soft/collector_opensvc/apps/web2py/gluon/dal.py", line 1282, in select
    rows = response(sql)
  File "/soft/collector_opensvc/apps/web2py/gluon/dal.py", line 1272, in response
    self.execute(sql)
  File "/soft/collector_opensvc/apps/web2py/gluon/dal.py", line 1359, in execute
    return self.log_execute(*a, **b)
  File "/soft/collector_opensvc/apps/web2py/gluon/dal.py", line 1353, in log_execute
    ret = self.cursor.execute(*a, **b)
  File "/soft/collector_opensvc/apps/web2py/gluon/contrib/pymysql/cursors.py", line 108, in execute
    self.errorhandler(self, exc, value)
  File "/soft/collector_opensvc/apps/web2py/gluon/contrib/pymysql/connections.py", line 182, in defaulterrorhandler
    raise Error(errorclass, errorvalue)
Error: (<type 'exceptions.AssertionError'>, AssertionError('Result length not requested length:\nExpected=21349484.  Actual=16777187.  Position: 28.  Data Length: 16777215',))